spring:
  datasource:
    url: jdbc:postgresql://postgres-library:5432/librarydb
    username: postgres
    password: 1122
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

