spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://localhost:5432/librarydb
    username: postgres
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /library/v3/api-docs
  swagger-ui:
    path: /library/swagger-ui.html