openapi: 3.0.0
info:
  title: Book Service API
  description: API Documentation for Book Service
  version: "1.0"
servers:
  - url: /books
paths:
  /:
    get:
      summary: Get all books
      description: Retrieves a list of all books available in the catalog.
      responses:
        '200':
          description: A list of books is successfully returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookDto'
  /id/{id}:
    get:
      summary: Get a book by its ID
      description: Fetches a single book using its unique identifier.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Book details are successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDto'
  /isbn/{isbn}:
    get:
      summary: Get a book by its ISBN
      description: Retrieves book details using its International Standard Book Number (ISBN).
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Book details are successfully returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDto'
  /add:
    post:
      summary: Add a new book
      description: Adds a new book to the catalog and returns the details of the added book.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookDto'
      responses:
        '201':
          description: The book is successfully created, and its details are returned.
  /{id}:
    put:
      summary: Update a book
      description: Updates the details of an existing book using its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookDto'
      responses:
        '200':
          description: The book is successfully updated.
    delete:
      summary: Delete a book
      description: Deletes a book from the catalog using its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The book is successfully deleted.
components:
  schemas:
    BookDto:
      type: object
      properties:
        id:
          type: integer
        isbn:
          type: string
        title:
          type: string
        description:
          type: string
        author:
          type: string
        genre:
          type: string